default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_development

test:
  <<: *default
  database: rails_api_test

production:
  <<: *default
  database: rails_api_production
  username: rails_api
  password: <%= ENV["RAILS_API_DATABASE_PASSWORD"] %>
